### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by westerncj** [Belicosus/AppAuth-Ionic#10]
I have my redirect_uri setup as `com.mycompany.myapp://token` and my URL_SCHEME in config.xml setup with `com.mycompany.myapp`. When this is called ` await this.safariViewController.show(optionSafari).toPromise();`, I see it go to my authorize endpoint with the redirect_uri, but I get an error from Safari saying it cannot open the page because the address is invalid.

How do I navigate to the correct place in my app? Am I missing some configuration?

**Comment by wi3land** [comment]
are you using identity server?

**Comment by westerncj** [comment]
Yes I'm using Identity Server, it looks like it's authorized successfully and tries to redirect to `com.mycompany.myapp`.

**Comment by wi3land** [comment]
are you getting anything coming into the custom url scheme? I know when i set this up i had an issue like this and it occurred because the safari wasn't getting redirected away from the safari browser into the custom scheme. 

I have a constant console.log in here now to make sure i get response back.
`      (<any>window).handleOpenURL = (url) => {   
        console.log(url);
        this.appAuth.AuthorizationCallback(url);  
      }
`

**Comment by westerncj** [comment]
I see that call in the app.component, but it never outputs anything to the console. It does seem like it's not using the custom scheme.
```
    (<any>window).handleOpenURL = url => {
        console.log('handleOpenURL', url);
        this.authService.AuthorizationCallback(url);
      };
```

**Comment by wi3land** [comment]
Have you tested your custom scheme?

**Comment by wi3land** [comment]
Go to this code pen link from your mobile and see if it opens your app
https://codepen.io/anon/pen/XBZzbE

**Comment by westerncj** [comment]
It doesn't open my application. Shouldn't it just be the following if my scheme is `com.mycompany.myapp` and my redirect_uri is `com.mycompany.myapp://token`?

`<h1><a href="com.mycompany.myapp">Click Here</a></h1>`

**Comment by wi3land** [comment]
the link i sent you should work, i tested it with a test app and it opened the app without issue.
it doesn't matter what you put after the :// but it should at least be com.mycompany.myapp://{{something}}
I think you probably have an issue with your custom-url-schema setup.

**Comment by westerncj** [comment]
Anyway I could get a copy of your test app so I can see what I might be doing wrong? I have the scheme set up
```

 <plugin name="cordova-plugin-customurlscheme" spec="^4.3.0">
    <variable name="URL_SCHEME" value="com.mycompany.myapp" />
</plugin

```

**Comment by wi3land** [comment]
there really was nothing to it,
I just ran: ionic start testapp blank
and added your schema: ionic cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME=com.mycompany.myapp

**Comment by westerncj** [comment]
Thanks for your help. It's definitely something with the URL SCHEME. I spun up a test app and it worked fine. I'm not sure what the difference would be between the test app and the example app provided. I have the same exact scheme set and it doesn't open in the example app.

**Comment by WhatsThatItsPat** [comment]
I think the customurlscheme plugin does a few other things. See if this is set correctly: https://developers.google.com/+/mobile/ios/getting-started#step_3_add_a_url_type

**Comment by westerncj** [comment]
So the issue was that my URL_SCHEME variable wasn't being updated. I had to actually remove the `cordova-plugin-customurlscheme` then re-add it with the URL_SCHEME variable for it to recognize it.
