### ISSUE TITLE
RefreshToken

### ISSUE THREAD

**Issue by j3ffb** [Belicosus/AppAuth-Ionic#2]
I am trying to work out how the refresh token is requested. I can see a `waitAuthenticated()` function, should this be polled by the app?
Thanks.

**Comment by chougaard** [comment]
`waitAuthenticated()` can be used in the app to await the authentication process. For example, we are using is in our API services. Before making authorized requests to the backend, we call `await waitAuthentication()`. That way, our asynchronous calls to the backend can check if we are authorized - even if we are in the middle of authorization of refreshing the token.
