### ISSUE TITLE
Security of holding token in back end storage

### ISSUE THREAD

**Issue by wi3land** [Belicosus/AppAuth-Ionic#3]
I am relatively new to this but i have managed to get project set up as a working solution for myself, Thanks for that. I was just wondering if it is totally secure using backend storage as a way of holding the token while the app is offline?

**Comment by chougaard** [comment]
stoageBackend uses [cordova-plugin-nativestorage](https://github.com/TheCocoaProject/cordova-plugin-nativestorage/blob/master/README.md). As described by themselves in their FAQ, thay are using: 
> Sharedpreferences in Android and NSUserDefaults in iOS.

This should be secure enough for this kind of information.

**Comment by wi3land** [comment]
Should have probably read that first, sorry to waste your time with this.
