### ISSUE TITLE
Inappbrowser support

### ISSUE THREAD

**Issue by wi3land** [Belicosus/AppAuth-Ionic#4]
Just to add another thing to this project i have set up an inappbrowser but i couldn't get it working using the event handler provided:
(<any>window).handleOpenURL = (url) => {
    this.completeAuthorization(url);
    console.log(url)
 };

I noticed that the read only mode for the safari view controller wasn't working on some of the android phones a tried. this is a problem for me, so i swapped it out completely and used inAppBrowser. Was there any reason in particular you were using safari view controller?

let options: InAppBrowserOptions = {
    location: 'no',
    zoom: 'no'
}
var loginScreen = this.inAppBrowser.create(url, '_self', options);
loginScreen .on('loadstart').subscribe(event => {
     if ((event.url).indexOf(request.redirectUri) === 0){
           loginScreen .close();  
           this.storageBackend.setItem(AUTHORIZATION_RESPONSE_KEY, event.url)
           this.completeAuthorizationRequestIfPossible();           
      }
});

**Comment by chougaard** [comment]
As stated in the Todo list in the readme of this, what is missing from this implementation if fallback to [InAppBrowser](https://ionicframework.com/docs/native/in-app-browser/).

The nice framework `cordova-plugin-safariviewcontroller` from @eddyverbruggen are utilizing the more modern [SafariViewControllers ](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller)(on iOS) and [ChromeTabs ](https://developer.chrome.com/multidevice/android/customtabs)(on Android). This is the recommended way to launch webviews from inside your app on the respective device types.
More about the advantages [here](https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller#5-advantages-over-inappbrowser)

Your implementation should probably be something like that of Eddy in his example [here](https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller#4-usage) where he calls `SafariViewController.isAvailable()`. Your implementation of InAppBrowser should be placed in the `else`-clause, when `available` is falls.
Please submit a pull-request if you are going to implement this 😃

**Comment by wi3land** [comment]
I have been struggling to get your version of the code to run correctly.
I basically have it working fine with inappbrowser but would love to use safari for the benifits you mentioned. I get that there is not eventlisteners in safari hence why you are doing the code below.

(<any>window).handleOpenURL = (url) => {
            this.completeAuthorization(url);
        };

I know this isn't really a question for here but i have been researching custom urls all day to understand this bit of code. Are you using the ionic deeplinking native api or how are you getting this to work?

**Comment by wi3land** [comment]
Dont worry I realised you were using the custom url scheme : https://github.com/EddyVerbruggen/Custom-URL-scheme i think?

I am going to try and implement using deeplinks so both safari and in app browser can use a common callback point. Im also unsure if Inappbrowsers eventlisteners are suggested by oauth2 so ill do some reading around this. So once i have got this sorted i'll submit a pull request.

**Comment by chougaard** [comment]
So, what you are saying is that the Custom Url Scheme libs from EddyVerbruggen aren't supported by InAppBrowser? So you can't link to the app from the InAppBrowser using this one?

**Comment by wi3land** [comment]
I have tested the ionic version of inAppBrowser and it doesn't appear to work. It is mentioned in the Custom Url Scheme Repo to use https://github.com/Onegini/cordova-plugin-inappbrowser instead. So I will try that and see if I have any luck. I also realized that the ionic deeplinks is not maintained so custom url is definitely the best path.
